# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deployment:

    runs-on: ubuntu-latest
    environment: Thor Server

    steps:
    - uses: actions/checkout@v3
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.THOR_SSHKEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.THOR_HOST }}
    - name: Deploy
      run: |
        ssh thor@${{ secrets.THOR_IP }} 'cd ${{ secrets.SERVER_PATH }} && git pull'
        ssh thor@${{ secrets.THOR_IP }} '. ${{ secrets.SERVER_PATH }}/venv/bin/activate && python -m pip install -r ${{ secrets.SERVER_PATH }}/requirements.txt'
        scp server/config/gunicorn.service root@${{ secrets.THOR_IP }}:/etc/systemd/system/gunicorn.service
        ssh root@${{ secrets.THOR_IP }} 'systemctl daemon-reload && systemctl start -u gunicorn'
        scp server/config/weatherino.nginx root@${{ secrets.THOR_IP }}:/etc/nginx/sites-available
        ssh root@${{ secrets.THOR_IP }} 'systemctl restart nginx'